name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: SolidifyDemo/actions-training-221205-shared/.github/workflows/shared-dotnet-ci.yml@41e88b745948e2da04fd6f53b8c78bfcbfc55f38

  deploy_dev:
    name: "Deploy to dev"
    environment: 
      name: dev
      url: ${{ steps.deploywebapp.outputs.webapp-url }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: webapp
        path: webapp

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: "actions-demo-api"
        package: webapp

    - name: az cli logout
      run: az logout   

  deploy_test:
    name: "Deploy to test"
    environment: 
      name: test
    needs: [deploy_dev]
    runs-on: ubuntu-latest
    steps:
    - name: "Testing workflow"
      run: echo "testing testing"

  run_test:
    name: "Running tests"
    environment: 
      name: test
    needs: [deploy_dev]
    runs-on: ubuntu-latest
    steps:
    - name: "Testing workflow"
      run: echo "testing testing"
      
  deploy_prod:
    name: "Deploy to prod"
    environment: 
      name: prod
    needs: [deploy_test, run_test]
    runs-on: ubuntu-latest
    steps:
    - name: "Testing workflow"
      run: echo "testing testing"
